version: '3'

services:
  postgres:
    image: "postgres:alpine"
    hostname: "postgres"
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=java'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'