version: '3'

services:
  postgres:
    image: "postgres:alpine"
    hostname: "postgres"
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=java'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
  java:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - rabbitmq
